version: '3'
services:

  web:
    build: ./web
    container_name: web01
    expose:
      - 5000
    depends_on:
      - db
    networks:
      - test_network

  nginx:
    build: ./nginx
    container_name: nginx01
    ports:
      - 8889:80
    depends_on:
      - web
    environment:
      - "TZ=Japan"
    restart: always
    networks:
      - test_network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx

  db:
    build: ./db
    container_name: db01
    volumes:
      - test_db_data:/val/lib/mysql
      - ./db/backup:/docker-entrypoint-initdb.d
    env_file:
      - ./db/conf.env
    environment:
      - "TZ=Japan"
    restart: always
    networks:
      - test_network

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin01
    env_file:
      - ./phpmyadmin/conf.env
    depends_on:
      - db
    ports:
      - 8888:80
    networks:
      - test_network

volumes:
    test_db_data: {}

networks:
  test_network:
    driver: bridge
